name: 🔥 Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇ Checkout Repository
        uses: actions/checkout@v4

      - name: ⚙ Install Firebase CLI
        run: npm install -g firebase-tools

      - name: 🚀 Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN1 }}
        run: firebase deploy --only hosting